/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:948c0d2d-cdd1-45b0-a622-a3398eb3c3b8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_klA0XQOl6",
    "aws_user_pools_web_client_id": "2n75ef91fov5tt8al36cuta5oh",
    "oauth": {}
};


export default awsmobile;
